# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mhasan <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/17 15:59:55 by mhasan            #+#    #+#              #
#    Updated: 2019/10/18 11:41:03 by mhasan           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
COMPILE = gcc -Wall -Wextra -Werror
SRC = ft_display_file.c

all: create

create:
	$(COMPILE) $(SRC) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)
